name: Code Check

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build
        run: mvn --batch-mode -DskipTests package

      - name: Test
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true test

      - name: Publish Test Report
        uses: dorny/test-reporter@v1
        if: always() # always run even if the previous step fails
        with:
            name: JUnit tests
            path: target/surefire-reports/*.xml
            reporter: java-junit
            fail-on-error: true
